# Generated by Django 2.1.3 on 2018-12-05 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('header', 'date')},
        ),
    ]
