# Generated by Django 2.1.3 on 2018-12-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_auto_20181205_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
